### ISSUE TITLE
Ориентация гипермаркета - клиент

### ISSUE THREAD

**Issue by amosov-f** [amosov-f/hypernavi#30]
Если с сервера приходит ориетация гипермаркета на Земле, то нужно по кнопке включать режим, в котором схема гипермаркета будет поворачиваться в зависимости от положения телефона в пространстве. Пример, http://www.javacodegeeks.com/2013/09/android-compass-code-example.html

**Comment by PolyakovD** [comment]
Зачем нужно вращение картинки в зависимости от ориентации телефона?

**Comment by BakharevK** [comment]
У нас на схеме есть буквы, они не вращаются.  И чтобы это исправить нужно знатно позаниматься анализом изображений либо на серве, с полным перелопачиванием интерфейса взаимодействия с клиентом, чтобы он перерисовывал буквы отдельно. Либо таскануть это на клиент, что еще более упорото.

**Comment by amosov-f** [comment]
Посмотрите вращение карты, к примеру, в 2ГИС-е. Там, кстати, названия улиц тоже не вращаются.
Пофиг на вращение подписей. Они и сейчас ориентированы абсолютно рандомно (для разных сетей совершенно по разному).
Для пользователя, на клиенте сейчас практически ничего не происходит. Вращение карты добавит ему хоть немного экшена. Тем более, для этого нужно совсем немного кода http://www.javacodegeeks.com/2013/09/android-compass-code-example.html
