### ISSUE TITLE
Классификатор схем гипермаркетов

### ISSUE THREAD

**Issue by amosov-f** [amosov-f/hypernavi#42]
Нужен классификатор, который по картинке будет говорить - схема гипермаркета это, или нет.
Скорее всего, будет несколько классификаторов - для схем "Окея", для схем "Ашана" и т.п. Это позволит еще дополнительно определять сеть гипермаркетов.

**Comment by amosov-f** [comment]
Нужно сделать хороших фич для Океев

**Comment by BakharevK** [comment]
Классификатор есть. Фичи тоже есть. Возможно будем еще добавлять.

**Comment by amosov-f** [comment]
Пока закроем
