### ISSUE TITLE
Ориентация гипермаркета - поиск

### ISSUE THREAD

**Issue by amosov-f** [amosov-f/hypernavi#46]
Надо научиться по подобным картинкам определять ориентацию гипермаркета
http://www.okmarket.ru/media/gallery/2012-07-27/Екатеринбург---схема-проезда.jpg
http://www.okmarket.ru/media/gallery/2015-01-28/lipetsk-map.jpg

**Comment by BakharevK** [comment]
Пока won'tfix. Будем делать ручками.
