### ISSUE TITLE
Нормальное размещение и вид кнопок

### ISSUE THREAD

**Issue by amosov-f** [amosov-f/hypernavi#47]
Кнопки +/-/обновить_позицию/вращение нужно разместить и сделать такими же, как в Яндекс.Навигаторе и в 2ГИС-е.

**Comment by PolyakovD** [comment]
Что имеется ввиду под видом кнопок?

**Comment by amosov-f** [comment]
Кнопки должны выглядеть похоже на
http://nicedroid.ru/uploads/posts/2014-05/1399445865_yandex-nav2.jpg
либо
https://yadi.sk/i/58LMHLYdixxQy

**Comment by PolyakovD** [comment]
То есть должны быть прозрачными?

**Comment by amosov-f** [comment]
Не обязательно

**Comment by amosov-f** [comment]
Кнопки "update position" и "off/on" следует сделать похожими на 
http://nicedroid.ru/uploads/posts/2014-05/1399445865_yandex-nav2.jpg
https://yadi.sk/i/58LMHLYdixxQy

**Comment by PolyakovD** [comment]
Done
