### ISSUE TITLE
Логотип, расстояние и адрес для показываемого гипермаркета

### ISSUE THREAD

**Issue by amosov-f** [amosov-f/hypernavi#49]
1) Слева сверху в углу должен быть логотип гипера. Ссылку на логотип будет присылать сервер #54,
2) Сверху по центру должен быть его адрес,
3) Под логотипом можно нарисовать расстояние до гипера.

**Comment by PolyakovD** [comment]
Если есть ссылка на Яндекс карты с местоположением гипера, то зачем нам расстояние до него и его адрес?

**Comment by amosov-f** [comment]
Не зря же, к примеру, в выдаче поисковиков есть не только ссылки. Пользователю гораздо удобнее видеть ответ сразу в выдаче.
Можно сделать так же, как в Яндекс.Навигаторе - сверху писать место, в котором находится юзер.

**Comment by amosov-f** [comment]
Ссылку на Яндекс.Карты тоже можно где-нибудь показать

**Comment by amosov-f** [comment]
Ссылку на Яндекс.Карты тоже можно где-нибудь показать

**Comment by amosov-f** [comment]
Возможно, дополнительную инфу стоит показывать по клику на какую-нибудь кнопку. Иначе просто все на экран не влезет.

**Comment by amosov-f** [comment]
Решили сделать так,
1) Слева сверху в углу должен быть логотип гипера. Ссылку на логотип будет присылать сервер https://github.com/amosov-f/hypernavi/issues/54,
2) Сверху по центру должен быть его адрес,
3) Под логотипом можно нарисовать расстояние до гипера.
