### ISSUE TITLE
Получить одобрение проекта от кураторов

### ISSUE THREAD

**Issue by amosov-f** [amosov-f/hypernavi#6]
Нужно отправить ТЗ кому-нибудь из кураторов и получить одобрение на продолжение работы над проектом в качестве летней практики
Дедлайн: 22 июля

**Comment by sir-chaos** [comment]
Письмо кураторам написано, ожидаю ответа

**Comment by BakharevK** [comment]
И как ожидание? Не устал ждать?

**Comment by sir-chaos** [comment]
Согласен, время ожидания вышло. Напишу Жене ВК. В остальном вопрос закрыт
