### ISSUE TITLE
Научиться передавать json-ы

### ISSUE THREAD

**Issue by sir-chaos** [amosov-f/hypernavi#8]
Научиться передавать с сервера на клиент json-ы. Должен быть написан рабочий код который реализует передачу композитной информации о гипермаркете.

**Comment by amosov-f** [comment]
Можно выбрать такой формат
```json
{
"meta": {}
"data": [{
"id": 1
"schema": "http://hypernavi.cloudapp.net/img/1bc29b36/f623ba82/aaf6724f/d3b16718.jpg", 
"position": {"lat": "60", "lon": "30"}
"address": "SPb"
}, {}, ...]
}
```

**Comment by BakharevK** [comment]
Мы выбрали другой фреймворк. 
Работать научились. Формат будем еще дорабатывать.
