### ISSUE TITLE
Доступ к схемам как к ресурсам на сервере

### ISSUE THREAD

**Issue by sir-chaos** [amosov-f/hypernavi#9]
Сделать доступ к схемам гипермеркетов как к статическим ресурсам на сервере (по ссылке, передаваемой на клиент)

**Comment by amosov-f** [comment]
Изображения должны храниться в файловой системе (не в ресурсах!). Путем до картинки может быть md5 хеш от нее, разделенный на части. К примеру, хешу 1bc29b36f623ba82aaf6724fd3b16718 будет соответствовать путь в файловой системе /root/1bc29b36/f623ba82/aaf6724f/d3b16718.
